"""initial_schema

Revision ID: 51b7a941e096
Revises: 
Create Date: 2026-05-10 19:54:15.703972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b7a941e096'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('dim_assumption',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_str', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dim_client',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_name')
    )
    op.create_table('dim_cost_center',
    sa.Column('cc_code', sa.String(), nullable=False),
    sa.Column('cc_name', sa.String(), nullable=False),
    sa.Column('bu', sa.String(), nullable=True),
    sa.Column('ou', sa.String(), nullable=True),
    sa.Column('los', sa.String(), nullable=True),
    sa.Column('legal_entity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cc_code')
    )
    op.create_table('dim_engagement_owner',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dim_fiscal_calendar',
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('fy_start_date', sa.Date(), nullable=False),
    sa.Column('fy_end_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fy')
    )
    op.create_table('imports',
    sa.Column('import_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('project_id_extracted', sa.String(), nullable=True),
    sa.Column('import_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_error', sa.Integer(), nullable=False),
    sa.Column('backup_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('import_id')
    )
    op.create_table('dim_resource',
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('resource_cost_center', sa.String(), nullable=True),
    sa.Column('legal_entity', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resource_cost_center'], ['dim_cost_center.cc_code'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('dim_week',
    sa.Column('week_id', sa.String(length=10), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('month_id', sa.String(length=7), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('fy_month', sa.Integer(), nullable=False),
    sa.Column('fy_week', sa.Integer(), nullable=True),
    sa.Column('fy_month_week', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['fy'], ['dim_fiscal_calendar.fy'], ),
    sa.PrimaryKeyConstraint('week_id')
    )
    with op.batch_alter_table('dim_week', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dim_week_fy_month_week'), ['fy_month_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_week_month_id'), ['month_id'], unique=False)

    op.create_table('fact_project',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_title', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('debtor_account', sa.String(), nullable=True),
    sa.Column('legal_entity', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('opportunity_name', sa.String(), nullable=True),
    sa.Column('chargeable', sa.String(), nullable=True),
    sa.Column('project_status', sa.String(), nullable=True),
    sa.Column('fy_closing', sa.Integer(), nullable=True),
    sa.Column('project_closing_date', sa.Date(), nullable=True),
    sa.Column('engagement_manager', sa.String(), nullable=True),
    sa.Column('engagement_manager_cc', sa.String(), nullable=True),
    sa.Column('engagement_partner', sa.String(), nullable=True),
    sa.Column('engagement_partner_cc', sa.String(), nullable=True),
    sa.Column('hours_actual', sa.Float(), nullable=True),
    sa.Column('gross_revenue', sa.Float(), nullable=True),
    sa.Column('bi_real_pct_todo', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('wip_provision', sa.Float(), nullable=True),
    sa.Column('net_revenue_act', sa.Float(), nullable=True),
    sa.Column('fees_as_expenses', sa.Float(), nullable=True),
    sa.Column('expenses_act', sa.Float(), nullable=True),
    sa.Column('lump_sum_act', sa.Float(), nullable=True),
    sa.Column('total_expenses_act', sa.Float(), nullable=True),
    sa.Column('billed_fees', sa.Float(), nullable=True),
    sa.Column('billed_expenses', sa.Float(), nullable=True),
    sa.Column('billed_amount', sa.Float(), nullable=True),
    sa.Column('wip', sa.Float(), nullable=True),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('iow_hours_total', sa.Float(), nullable=True),
    sa.Column('iow_contract_value', sa.Float(), nullable=True),
    sa.Column('iow_net_revenue', sa.Float(), nullable=True),
    sa.Column('iow_expenses', sa.Float(), nullable=True),
    sa.Column('iow_lump_sum', sa.Float(), nullable=True),
    sa.Column('bi_report_url', sa.Text(), nullable=True),
    sa.Column('last_import_id', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Integer(), nullable=False),
    sa.Column('last_seen_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['dim_client.client_id'], ),
    sa.ForeignKeyConstraint(['last_import_id'], ['imports.import_id'], ),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['imports.import_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('fact_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_project_is_stale'), ['is_stale'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_project_project_status'), ['project_status'], unique=False)

    op.create_table('fact_project_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('changed_fields', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.import_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['fact_project.project_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('fact_project_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_project_history_project_id'), ['project_id'], unique=False)

    op.create_table('fact_timesheet',
    sa.Column('timesheet_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('week_id', sa.String(length=10), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=True),
    sa.Column('fy_month_week', sa.String(length=12), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('document_item_text', sa.Text(), nullable=True),
    sa.Column('hours_actual', sa.Float(), nullable=True),
    sa.Column('gross_revenue', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('wip_provision', sa.Float(), nullable=True),
    sa.Column('net_revenue_actual', sa.Float(), nullable=True),
    sa.Column('gross_rate', sa.Float(), nullable=True),
    sa.Column('net_rate', sa.Float(), nullable=True),
    sa.Column('resource_cost_center', sa.String(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Integer(), nullable=False),
    sa.Column('last_seen_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.import_id'], ),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['imports.import_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['fact_project.project_id'], ),
    sa.ForeignKeyConstraint(['resource_cost_center'], ['dim_cost_center.cc_code'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['dim_resource.resource_id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['dim_week.week_id'], ),
    sa.PrimaryKeyConstraint('timesheet_id')
    )
    with op.batch_alter_table('fact_timesheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_timesheet_fy'), ['fy'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_timesheet_is_stale'), ['is_stale'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_timesheet_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_timesheet_resource_cost_center'), ['resource_cost_center'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_timesheet_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_timesheet_week_id'), ['week_id'], unique=False)
        batch_op.create_index('ix_timesheet_fy_cc', ['fy', 'resource_cost_center'], unique=False)
        batch_op.create_index('ix_timesheet_project_week', ['project_id', 'week_id'], unique=False)

    op.create_table('forecast_override',
    sa.Column('override_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('month_id', sa.String(length=7), nullable=False),
    sa.Column('override_hours', sa.Float(), nullable=True),
    sa.Column('override_net_revenue', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['fact_project.project_id'], ),
    sa.PrimaryKeyConstraint('override_id')
    )
    with op.batch_alter_table('forecast_override', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_override_project_id'), ['project_id'], unique=False)
        batch_op.create_index('uq_override_project_month', ['project_id', 'month_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_override', schema=None) as batch_op:
        batch_op.drop_index('uq_override_project_month')
        batch_op.drop_index(batch_op.f('ix_forecast_override_project_id'))

    op.drop_table('forecast_override')
    with op.batch_alter_table('fact_timesheet', schema=None) as batch_op:
        batch_op.drop_index('ix_timesheet_project_week')
        batch_op.drop_index('ix_timesheet_fy_cc')
        batch_op.drop_index(batch_op.f('ix_fact_timesheet_week_id'))
        batch_op.drop_index(batch_op.f('ix_fact_timesheet_resource_id'))
        batch_op.drop_index(batch_op.f('ix_fact_timesheet_resource_cost_center'))
        batch_op.drop_index(batch_op.f('ix_fact_timesheet_project_id'))
        batch_op.drop_index(batch_op.f('ix_fact_timesheet_is_stale'))
        batch_op.drop_index(batch_op.f('ix_fact_timesheet_fy'))

    op.drop_table('fact_timesheet')
    with op.batch_alter_table('fact_project_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_project_history_project_id'))

    op.drop_table('fact_project_history')
    with op.batch_alter_table('fact_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_project_project_status'))
        batch_op.drop_index(batch_op.f('ix_fact_project_is_stale'))

    op.drop_table('fact_project')
    with op.batch_alter_table('dim_week', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dim_week_month_id'))
        batch_op.drop_index(batch_op.f('ix_dim_week_fy_month_week'))

    op.drop_table('dim_week')
    op.drop_table('dim_resource')
    op.drop_table('imports')
    op.drop_table('dim_fiscal_calendar')
    op.drop_table('dim_engagement_owner')
    op.drop_table('dim_cost_center')
    op.drop_table('dim_client')
    op.drop_table('dim_assumption')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
